name: 'GoCD Jsonnet'
description: 'This action checks Jsonnet files to build, lint, fmt and ensure commited pipelines are up-to-date'
inputs:
  jsonnet-dir:
    description: 'The path for jsonnet files'
    required: true
    default: 'gocd/templates'
  generated-dir:
    description: 'The path for jsonnet files are rendered to'
    required: true
    default: 'gocd/generated-pipelines'
  render-as-single-file:
    descript: 'Whether to render as a single file or multiple'
    type: boolean
    default: true
    required: true
  jb-install:
    description: "When true, jb install will be run"
    type: boolean
    default: false
  check-for-changes:
    description: "If the generated pipelines are commited to your repo, set this to true to ensure the PR is up-to-date (i.e. the yaml has been built with all jsonnet changes)"
    type: boolean
    default: false
  convert-to-yaml:
    description: "If the generated pipelines should be converted from json to yaml"
    type: boolean
    default: false
  render-jsonnet-files:
    description: "Whether the action should render jsonnet files"
    type: boolean
    default: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

    - name: Install go
      uses: actions/setup-go@19bb51245e9c80abacb2e91cc42b33fa478b8639 # v4
    - name: Install Jsonnet
      shell: bash
      run: |
        go install github.com/google/go-jsonnet/cmd/jsonnet@latest
        go install github.com/google/go-jsonnet/cmd/jsonnetfmt@latest
        go install github.com/google/go-jsonnet/cmd/jsonnet-lint@latest
        go install -a github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb@latest
        go install github.com/mikefarah/yq/v4@latest

    - name: jsonnet bundler install
      shell: bash
      if: ${{ inputs.jb-install == 'true' }}
      env:
        JSONNET_DIR: ${{ inputs.jsonnet-dir }}
      run: |
        cd "$JSONNET_DIR"
        jb install

    - name: jsonnetfmt
      id: jsonnetfmt
      shell: bash
      env:
        JSONNET_DIR: ${{ inputs.jsonnet-dir }}
      run: |
        set -eou pipefail

        # Remove multiple slashes from path
        ignore_path=$(echo "$JSONNET_DIR/vendor/*" | sed 's|/\+|/|g')
        for i in $(find "$JSONNET_DIR" -type f \( -name '*.libsonnet' -o -name '*.jsonnet' \) -not -path "$ignore_path" ); do
          echo -e "\n📋 Checking format of: $i\n";
          jsonnetfmt --test $i
        done

    - name: jsonnetfmt error
      shell: bash
      if: steps.jsonnetfmt.outcome == 'failure' && always()
      run: echo -e "\n\n⚠️ Please run 'jsonnetfmt -i **/*.jsonnet && jsonnetfmt -i **/*.libsonnet' to fix formatting issues.\n\n"

    - name: jsonnet-lint
      shell: bash
      env:
        JSONNET_DIR: ${{ inputs.jsonnet-dir }}
      run: |
        set -eou pipefail

        # Remove multiple slashes from path
        ignore_path=$(echo "$JSONNET_DIR/vendor/*" | sed 's|/\+|/|g')
        for i in $(find "$JSONNET_DIR" -type f \( -name '*.libsonnet' -o -name '*.jsonnet' \) -not -path "$ignore_path" ); do
          echo -e "\n🔬 Linting: $i\n";
          jsonnet-lint -J "$JSONNET_DIR/vendor" $i
        done

    - name: Remove existing pipelines to ensure we don't have lingering pipelines
      shell: bash
      env:
        GENERATED_DIR: ${{ inputs.generated-dir }}
      run: |
        rm -rf   "$GENERATED_DIR"
        mkdir -p "$GENERATED_DIR"

    - name: Render Multiple Files
      shell: bash
      if: ${{ inputs.render-jsonnet-files =='true' && inputs.render-as-single-file == 'false' }}
      env:
        JSONNET_DIR: ${{ inputs.jsonnet-dir }}
        GENERATED_DIR: ${{ inputs.generated-dir }}
      run: |
        set -eou pipefail

        ignore_path=$(echo "$JSONNET_DIR/vendor/*" | sed 's|/\+|/|g')
        for i in $(find "$JSONNET_DIR" -type f \( -name '*.jsonnet' \) -not -path "$ignore_path" ); do
          echo -e "\n🖨️ Rendering: $i\n";
          jsonnet \
            -J "$JSONNET_DIR/vendor" \
            --ext-code output-files=true \
            -m "$GENERATED_DIR" \
            $i;
        done

    - name: Render Single File
      shell: bash
      if: ${{ inputs.render-jsonnet-files =='true' && inputs.render-as-single-file == 'true' }}
      env:
        JSONNET_DIR: ${{ inputs.jsonnet-dir }}
        GENERATED_DIR: ${{ inputs.generated-dir }}
      run: |
        set -eou pipefail

        ignore_path=$(echo "$JSONNET_DIR/vendor/*" | sed 's|/\+|/|g')
        for i in $(find "$JSONNET_DIR" -type f \( -name '*.jsonnet' \) -not -path "$ignore_path" ); do
          echo -e "\n🖨️ Rendering: $i\n";
          jsonnet \
            -J "$JSONNET_DIR/vendor" \
            --ext-code output-files=false \
            -o "$GENERATED_DIR/all-pipelines.yaml" \
            $i;
        done

    - name: Convert json to yaml
      shell: bash
      if: ${{ inputs.convert-to-yaml == 'true' }}
      env:
        GENERATED_DIR: ${{ inputs.generated-dir }}
      run: |
        set -eou pipefail

        for i in $(find "$GENERATED_DIR" -type f \( -name '*.yaml' \) ); do
          echo -e "\n💱 Converting to yaml: $i\n";
          yq -p json -o yaml -i $i;
        done

    - name: Fail if generated pipelines have changed
      if: ${{ inputs.check-for-changes == 'true' }}
      shell: bash
      run: if [ -n "$(git status --porcelain)" ] ; then git status; exit 1; fi
