name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to publish (i.e. v1.0.0)'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: actions/github-script@00f12e3e20659f42342b1c0226afda7f7c042325 # v6
        env:
          VERSION: ${{ inputs.version }}
        with:
          script: |
            const publish = require('./.github/scripts/publish.js');
            publish({context, octokit: github});
