name: Self Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  self-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        name: Render multiple files and check for changes
        with:
          jsonnet-dir: ./testdata/
          generated-dir: ./testdata/generated/
          render-as-single-file: false
          check-for-changes: true
      - uses: ./
        name: Render single file
        with:
          jsonnet-dir: ./testdata/
          generated-dir: ./testdata/generated/
          convert-to-yaml: true
